#!/bin/bash
set -x
set -e
set -o pipefail
cd ~/.xmonad
cabal new-build
x=$(PATH="${PATH/$HOME\/.local\/bin:/}" cabal new-exec --verbose=0 --offline sh -- -c 'which xmonad')
[ ! -x "$x" ] && echo "Couldn't find executable xmonad in dist-newstyle" && exit 1
cp -uf "$x" "$1"
xc=$(PATH="${PATH/$HOME\/.local\/bin:/}" cabal new-exec --verbose=0 --offline sh -- -c 'which xmonadctl')
[ ! -x "$xc" ] && echo "Couldn't find executable xmonadctl in dist-newstyle" && exit 1
cp -uf "$xc" ~/.local/bin/xmonadctl
xmonad --restart
